### ISSUE TITLE
segmentation fault when import tensorboardX

### ISSUE THREAD

**Issue by Liu0329** [lanpa/tensorboardX#178] opened 2018-06-27 12:20 UTC
When I import tensorboardX
then shows
Segmentation fault (core dumped)
I have tried conda, pip, pip from source.

**Comment by lanpa** [comment] 2018-06-27 16:42
Did you also import other packages?

**Comment by Liu0329** [comment] 2018-06-28 06:06
No.

**Comment by rxqy** [comment] 2018-07-03 06:18
Hi, I met a similar problem here, but my problem is with my tensorflow
Can you successfully import tensorflow in python?

**Comment by lanpa** [comment] 2018-07-03 07:35
@Liu0329 @rxqy, I can't reproduce without further information. I recommend using anaconda's virtual environment to build do the test.

**Comment by rxqy** [comment] 2018-07-03 07:37
Nope, I fixed the problem by reinstalling tensorflow, there was something wrong with it.

**Comment by lanpa** [comment] 2018-07-03 07:46
@rxqy what's the error message?

**Comment by rxqy** [comment] 2018-07-03 07:49
When I import tensorboard,  I got segmentation fault,
then I tried to import tensorflow, there was another strange error, but I didn't really remember.
So I just reinstalled tensorflow, and the problem is fixed, guess something is wrong in my environment.

**Comment by lanpa** [comment] 2018-07-03 07:52
import tensorboard or import tensorboardX? Did you install from source or from pip?

**Comment by rxqy** [comment] 2018-07-03 07:55
tensorboardX, from conda

**Comment by lanpa** [comment] 2018-07-03 07:57
I haven't tried conda yet. Would you try with source or pip?

**Comment by rxqy** [comment] 2018-07-03 07:59
ehhhhh, I fixed the problem myself. Everything's fine with me.
Saw a similar issue, and thought maybe I could help.

**Comment by Liu0329** [comment] 2018-07-04 12:11
@rxqy @lanpa I use python 3.6 with pytorch 0.4. The error shows when I enter python and import nothing but tensorboardX. It is not related to other modules.

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorboardX
Segmentation fault (core dumped)

**Comment by lanpa** [comment] 2018-07-04 13:33
@Liu0329 Please use https://stackoverflow.com/questions/16731115/how-to-debug-a-python-segmentation-fault?rq=1 to get more information

**Comment by MilanKolkata** [comment] 2018-07-24 22:15
@Liu0329 I also have the same problem and have no idea to fix it. Have you fixed it for now?

**Comment by Liu0329** [comment] 2018-07-26 01:43
@MilanKolkata No

**Comment by lanpa** [comment] 2018-07-30 13:56
@MilanKolkata Please use https://stackoverflow.com/questions/16731115/how-to-debug-a-python-segmentation-fault?rq=1 to get more information (the result of pip list will be helpful too)

**Comment by szrlee** [comment] 2018-10-07 16:37
same issue

**Comment by szrlee** [comment] 2018-10-07 16:42
> same issue

after update this package, the problem was solved.
```
libprotobuf: 3.6.0-hd28b015_0 conda-forge --> 3.6.0-hdbcaa40_0
```

**Comment by dragon9001** [comment] 2018-11-25 16:50
@szrlee your solution works for me, I update my package using:
conda update libprotobuf

the version change is:
    libprotobuf: 3.6.1-hd28b015_0 conda-forge --> 3.6.1-hd408876_0 defaults

**Comment by leixiang90** [comment] 2019-01-16 13:34
conda install libprotobuf=3.6.1
this works for me

**Comment by lamnguyen95** [comment] 2019-04-22 08:36
I was facing the same issue when installing tensorboardX offline.

Turns out that was version mismatch between protobuff and libprotobuff. Both must be at version 3.6.1

**Comment by lanpa** [comment] 2019-07-11 14:32
addressed in fix #467.

**Closed by lanpa** 2019-07-11 14:32 UTC

**Comment by RizhaoCai** [comment] 2019-07-25 10:24
> conda install libprotobuf=3.6.1

Thank you. It also works for me.
