### ISSUE TITLE
TypeError: 'GraphDef' object does not support indexing

### ISSUE THREAD

**Issue by Fangyh09** [lanpa/tensorboardX#220] opened 2018-09-04 02:31 UTC
I used nested model.
Doesn't it support nested model?

**Comment by lanpa** [comment] 2018-09-26 16:10
Hi, can you provide some code to reproduce?

**Comment by SystemErrorWang** [comment] 2018-10-08 03:55
Same problem here, below is the error log:

Error occurs, No graph saved
Checking if it's onnx problem...
Your model fails onnx too, please report to onnx team

Traceback (most recent call last):
  File "/home/wangxinrui/FasterRcnn/train.py", line 134, in <module>
    train()
  File "/home/wangxinrui/FasterRcnn/train.py", line 100, in train
    writer.add_graph(trainer, [img, bbox, label, scale])
  File "/home/wangxinrui/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 520, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/wangxinrui/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 107, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object does not support indexing

Process finished with exit code 1

**Comment by Mojomotte** [comment] 2018-10-15 13:53
I get the exact some error when using a nested model. Any solutions so far?

**Comment by lc17721825** [comment] 2018-11-04 02:19
hi lanpa, thanks for your great tensorboardx. when I add_graph a nested model, I meet the same problem as SystemErrorWang. Is that something wrong with nested model? Thanks in advance.@lanpa

**Comment by KongYuJL** [comment] 2019-01-01 04:56
I also got the same issue

**Comment by nmakes** [comment] 2019-02-15 08:25
Same issue here as well. I'm having a nested model and getting this error.

**Comment by nmakes** [comment] 2019-02-15 08:34
Same issue here as well. I'm having a nested model and getting this error. My model contains a resnet18 with a tied decoder (all conv_transpose weights of the decoder are tied to the conv layers of resnet18). I have defined the conv_transpose block as follows. It takes the corresponding conv layer to get the information about weights, stride etc.:

`
class InvConv2d(nn.Module):

	def __init__(self, conv_layer, stride = None, padding = None, output_padding = (0, 0)):

		super(InvConv2d, self).__init__()

		self.conv = conv_layer
		if stride == None:
			self.stride = self.conv.stride
		else:
			self.stride = stride
		if padding == None:
			self.padding = self.conv.padding
		else:
			self.padding = padding
		self.output_padding = output_padding

	def forward(self, x):
		ret = F.conv_transpose2d(x, weight = self.conv.weight, bias = None, stride = self.conv.stride, padding = self.conv.padding, output_padding = self.output_padding)
		return ret
`

I am using these transpose convolutions in my weight - tied decoder network. I need to visualize the graph to see whether the activations are being passed correctly.

Any fix for this yet?

**Comment by rahulptel** [comment] 2019-04-08 20:52
I am also facing the same issue while trying to visualize a nested model.

**Comment by shiranD** [comment] 2019-04-21 20:17
I got the same error. In my case I was using add_graph(model, input), and I suspect the problem was because I sent an integer and not a tensor (the input tuple aside from the input tensors also contained an integer). When casting the integer as a tensor didn't work since the code detected that I need it to be an integer in the forward pass of the model. Any chance that it will allow for ints as well?

**Comment by lanpa** [comment] 2019-04-25 18:45
@shiranD Does `x = model(input)` runs without problem?

**Comment by shiranD** [comment] 2019-04-25 23:31
This input seems to be producing a graph or at least not giving any error. Now the problem is that it refuses to display it on the board. Thanks for responding so quickly!

**Comment by hanamizukigakki** [comment] 2019-05-07 13:55
> Same problem here, below is the error log:
> 
> Error occurs, No graph saved
> Checking if it's onnx problem...
> Your model fails onnx too, please report to onnx team
> 
> Traceback (most recent call last):
> File "/home/wangxinrui/FasterRcnn/train.py", line 134, in 
> train()
> File "/home/wangxinrui/FasterRcnn/train.py", line 100, in train
> writer.add_graph(trainer, [img, bbox, label, scale])
> File "/home/wangxinrui/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 520, in add_graph
> self.file_writer.add_graph(graph(model, input_to_model, verbose))
> File "/home/wangxinrui/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 107, in add_graph
> graph = graph_profile[0]
> TypeError: 'GraphDef' object does not support indexing
> 
> Process finished with exit code 1

I have got the same problem, if any advices?

**Comment by wuyifan18** [comment] 2019-05-28 05:40
I have got the same problem, if any advices?

**Comment by 1zgh** [comment] 2019-06-24 11:08
Your model cannot be exported by onnx, please report to onnx team
    w.add_graph(net, (x))
  File "/home/zhang/.conda/envs/torch0.4-caffe/lib/python3.6/site-packages/tensorboardX/writer.py", line 697, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/zhang/.conda/envs/torch0.4-caffe/lib/python3.6/site-packages/tensorboardX/writer.py", line 137, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object does not support indexing

I have the same problem,How can I do?

**Comment by lanpa** [comment] 2019-07-01 18:24
@1zgh You might need to update your torch version as well as tensorboardX.

**Comment by cheerss** [comment] 2019-07-04 03:37
Aha! I have met the same problem as you but I have solved it now. I use pytorch1.1.0 and

**Comment by lanpa** [comment] 2019-07-04 16:44
@cheerss 
pytorch model can be exported to onnx. And before tensorboardX 1.7, it relies on the exported onnx graph to draw on tensorboard. 
And now the onnx used in add_graph have replaced with JIT since https://github.com/lanpa/tensorboardX/commit/b59a8a0237eaaeff8cb82e1d0a06c5bcac105b9b

This should be less problematic.

**Comment by seenitall** [comment] 2019-07-05 09:19
@lanpa -- same here: tensorboardX v1.8, torch 1.1.0, torchvision 0.3, model=DeepLabV3 (torchvision), model_input=torch.cuda.FloatTensor (torch.float32)

**Comment by lanpa** [comment] 2019-07-09 14:11
@seenitall Can you post the whole error message?

**Comment by 1zgh** [comment] 2019-07-10 00:13
> @1zgh You might need to update your torch version as well as tensorboardX.

Thanks, I update the verison. And it works.

**Comment by lanpa** [comment] 2019-07-17 14:14
Close this since this thread is pretty old, and many context is outdated. Please open an issue and follow the issue template if needed.

**Closed by lanpa** 2019-07-17 14:14 UTC

**Comment by Devin879176** [comment] 2019-08-06 07:21
Error occurs, No graph saved
Checking if it's onnx problem...
Your model fails onnx too, please report to onnx team
Traceback (most recent call last):
  File "test.py", line 133, in <module>
    prefetch_test(opt)
  File "test.py", line 75, in prefetch_test
    ret = detector.run(pre_processed_images)
  File "/home/devin/Project/Pycharm/CenterNet/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
I get the some exact problem, how do you solve it?
 
 File "/home/devin/Project/Pycharm/CenterNet/CenterNet/src/lib/detectors/multi_pose.py", line 51, in process
    w.add_graph(self.model, dummy_input)
  File "/home/devin/anaconda3/envs/CenterNet/lib/python3.6/site-packages/tensorboardX/writer.py", line 520, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/devin/anaconda3/envs/CenterNet/lib/python3.6/site-packages/tensorboardX/writer.py", line 107, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object does not support indexing
