### ISSUE TITLE
TypeError: 'GraphDef' object does not support indexing

### ISSUE THREAD

**Issue by xuehui1991** [lanpa/tensorboardX#499] opened 2019-08-26 09:18 UTC
Getting the error

```
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    train(epoch)
  File "main.py", line 97, in train
    w.add_graph(net, (input,))
  File "/home/x/miniconda3/envs/py3.6_tensorboard/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/x/miniconda3/envs/py3.6_tensorboard/lib/python3.6/site-packages/tensorboardX/writer.py", line 138, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object does not support indexing

```

when I try to dump the graph of **Resnet18** (model code is [here)](https://github.com/kuangliu/pytorch-cifar)

```
            with SummaryWriter(comment = 'resnet18') as w:
                w.add_graph(net, (input,))
```

I am using Pytorch 1.2.0 and TensorboardX 1.8

Could you help me to fix this problem?

**Comment by lusofa** [comment] 2019-08-27 08:10
show your code.I am not sure the cause of ''GraphDef' object does not support indexing' error, but sometimes put the  data type error right can solve this problem.
so check your code, maybe there is some data type error

**Comment by lanpa** [comment] 2019-10-23 15:30
There is no problem with TensorboardX 1.9 + pytorch 1.3. So close this.

**Closed by lanpa** 2019-10-23 15:30 UTC
