### ISSUE TITLE
demo_graph.py error on pytorch 0.4.0

### ISSUE THREAD

**Issue by danakianfar** [lanpa/tensorboardX#99] opened 2018-03-10 17:01 UTC
I tried running the demo_graph.py and got the following error.

```
python demo_graph.py 
Traceback (most recent call last):
  File "demo_graph.py", line 56, in <module>
    w.add_graph(model, (dummy_input, ))
  File "/home/dana/Desktop/tensorboard-pytorch/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/dana/Desktop/tensorboard-pytorch/tensorboardX/graph.py", line 52, in graph
    trace, _ = torch.jit.trace(model, args)
TypeError: 'function' object is not iterable
```
The return of `torch.jit.trace` is [this wrapper](https://github.com/pytorch/pytorch/blob/master/torch/jit/__init__.py#L460), from [this commit](https://github.com/pytorch/pytorch/pull/5409)

I'm using the Python 3.6 on Ubuntu 16.04
- `torch==0.4.0` built from source
- `tensorboardX==1.1`
- `tensorboard==1.6.0`

Edit: Updated my pytorch version

**Comment by lanpa** [comment] 2018-03-11 17:27
can't reproduce :(  
`torch==0.3.1, tensorboardX==1.1`

The 0.3.1 is from conda. Did you install 0.3.1 from source? Not sure if there are differences...

**Comment by danakianfar** [comment] 2018-03-11 17:52
Oh yeah, I installed from source actually. My GPU is a bit old.

**Comment by lanpa** [comment] 2018-03-11 18:15
Since you build from source, why not go for 0.4 lol. Another choice is to install `pytorch-cpu` in virtual env for graph plotting.

**Comment by danakianfar** [comment] 2018-03-12 14:01
Thanks for pointing this out. It turns out that I was actually using PyTorch 0.4.0. My initial mistake in report 0.3.1 was due to the fact that torchvision had installed conda's pytorch. Anyhow, the problem I suppose is still with 0.4 and goes back to the wrapper function I pointed to initially. 

I'll try with `pytorch-cpu`, thanks

**Comment by AlbertZhangHIT** [comment] 2018-03-13 13:17
Hi, I also tried running the demo_graph.py, but the graph on tensorboard is like
![graph](https://user-images.githubusercontent.com/29504198/37343678-38c22602-2703-11e8-9101-41ce039d78be.png)
I'm using the Python 3.5 on Ubuntu 14.04

- `torch==0.3.1` from `conda`

- `tensorboardX=1.1`

- `tensorboard` =1.6.0

**Comment by danakianfar** [comment] 2018-03-17 15:26
Why is this issue closed? Was anyone able to reproduce the issue with pytorch 0.4?

**Comment by lanpa** [comment] 2018-03-17 15:43
@danakianfar I thought `pytorch-cpu` works for you. Have you tried with newest pytorch 0.4?

**Comment by danakianfar** [comment] 2018-03-17 15:48
@lanpa Sorry, I messed up originally with my description. I only had pytorch 0.4 initially so the problem is in fact with pytorch 0.4. I think I figured it out though, I'm preparing a pull request now.

**Comment by xiongzhp** [comment] 2018-03-20 09:07
I don't think this issue has been fixed
For Python 3.5.4 on Ubuntu 16.04

torch==0.4.0 built from source
tensorboardX==1.1
tensorboard==1.6.0
I reproduced the issue exactly

**Comment by danakianfar** [comment] 2018-03-20 09:21
@xiongzhp Perhaps you can try this [pull request](https://github.com/lanpa/tensorboard-pytorch/pull/106) and let us know if it also works for you

**Comment by xiongzhp** [comment] 2018-03-20 09:50
@danakianfar   Thank you so much! Because I just installed TensorboardX from source, I thought your pull request has been merged, but not yet. I tried your code, it works great.

**Comment by xiongzhp** [comment] 2018-03-20 11:39
> RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got numpy.ndarray

Is this error in [#109](https://github.com/lanpa/tensorboard-pytorch/issues/109) related to the current issue?

**Comment by backpropper** [comment] 2018-04-26 06:32
`demo_graph.py` works perfectly. But if I try to save my own model it gievs this error:
`Error occurs, checking if it's onnx problem...
Your model fails onnx too, please report to onnx team
No graph saved`

Also is [this](https://github.com/lanpa/tensorboard-pytorch/blob/747f233eafb5a5210b68573d63b7d909011b75df/demo_graph.py#L48) bug rectified now?

**Comment by lanpa** [comment] 2018-04-26 06:53
@backpropper Because add_graph is based on onnx and some operation in your model cannot exported by onnx. you have to file a issue to them. The bug you mentioned should be solved, I will test it later.

**Comment by WenmuZhou** [comment] 2018-05-08 11:45
I mee the the error, my model is `torchvision.models.AlexNet`
```sh
Your model fails onnx too, please report to onnx team
```

**Comment by lanpa** [comment] 2018-05-08 13:14
@WenmuZhou Does the error come from `demo_graph.py`?

**Comment by WenmuZhou** [comment] 2018-05-09 00:15
@lanpa I have fixed my error , the code write network to tensorboard must before `model.to(device)`
```python
model = torchvision.models.AlexNet(num_classes=10)
# 准备写tensorboard, 必须放在'.to(device)'之前，不然会报错
writer = SummaryWriter()
dummy_input = torch.autograd.Variable(torch.rand(1, 3, 227, 227))
writer.add_graph(model=model, input_to_model=(dummy_input, ))

model = model.to(device)
```

**Comment by WenmuZhou** [comment] 2018-05-17 01:47
so the input data and the model must on same device

**Comment by xwjBupt** [comment] 2018-10-23 14:12
so ,how should i do to fix this problem?

Error occurs, No graph saved
Checking if it's onnx problem...
Your model fails onnx too, please report to onnx team

torch = 0.4.1
tensorboard = 1.8
tensorboardX = 1.4

here is my code:

`   cfg = './cfg/yolov3.cfg'
    model = DarkNet(cfg)
    imgfile = 'dog-cycle-car.png'
    img = get_test_input(imgfile)
    print (model)
    print (img)
    with SummaryWriter(comment='DarkNet') as w:
        w.add_graph(model,input_to_model = img)
`
what should i do?Thank you so much!!

**Comment by lanpa** [comment] 2018-12-10 14:20
@xwjBupt Would you like test your code with pytorch 1.0.0 + tensorboardX1.5?

**Comment by snehilverma41** [comment] 2019-04-24 04:44
**PyTorch** (torch) version: **1.0.1.post2**
**Tensorboard** version: **1.12.0**
**TensorboardX** version: **1.6**

Running `demo_graph.py`

Generates the following error:
```
expect error here:
Error occurs, No graph saved
Checking if it's onnx problem...
Your model fails onnx too, please report to onnx team
```
And the graph looks like this:
![image](https://user-images.githubusercontent.com/31213467/56632902-96b66300-6621-11e9-98a3-d5671826bdaa.png)

How should I fix this issue? (@lanpa)

**Comment by ywatanabe1989** [comment] 2019-06-14 23:51
In my case, a model not on GPU but on CPU was correctly displayed. However, RNN models didn't seem to be supported by ONNIX anyway.

**Comment by aviaefrat** [comment] 2019-06-30 16:19
@snehilverma41 notice the "expect error here:" line in the output. To my understanding, this error is expected. Check the [source code](https://github.com/lanpa/tensorboardX/blob/master/examples/demo_graph.py#L269).

Regarding your graph output, that seems like the correct graph for the [LinearInLinear Module](https://github.com/lanpa/tensorboardX/blob/master/examples/demo_graph.py#L11). To view graphs of other modules, try the `run` dropdown in tensorboard:
![tensorboard ui](https://user-images.githubusercontent.com/11952207/60399345-dfcbeb80-9b6b-11e9-8b0e-bec6e9f94ab1.png)

**Comment by lanpa** [comment] 2019-07-10 16:41
@ywatanabe1989 Not sure what RNN are you using, but those in `demo_graph.py` should work with onnx. BTW in tensorboardX v1.8 ONNX is replaced by JIT so more pytorch models should be supported now.

**Comment by lanpa** [comment] 2019-07-10 16:43
Closing this as pytorch 0.4 is legacy and totally new implementation of add_graph is release in tensorboardX 1.8. Please open a new issue if needed. (and follow the issue template)

**Closed by lanpa** 2019-07-10 16:43 UTC
Labels: onnx
