### ISSUE TITLE
HParam support

### ISSUE THREAD

**Issue by danielbraun89** [lanpa/tensorboardX#411] opened 2019-04-16 12:55 UTC
Can we get an "add_hparam" that will mimic the functionality of the Hparam plugin in tensorboard 2? (https://www.tensorflow.org/tensorboard/r2/hyperparameter_tuning_with_hparams)

**Comment by diogoseca** [comment] 2019-04-19 15:17
This is a duplicate of #381

**Closed** 2019-10-22 14:53 UTC
